name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [ main ]   # publica quando fizer commit no main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Usamos "npm install" (não 'npm ci') para não exigir package-lock.json
      - name: Install dependencies
        run: npm install

      # Garante que existe script "build" no package.json
      - name: Build
        run: npm run build

      # Envia a pasta "dist" (padrão do Vite) para o Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
